apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: {{ .Values.nodeExporter.port }}
      targetPort: {{ .Values.nodeExporter.port }}
