version: "3.8"
services:
  grafana:
    image: grafana/grafana:10.4.0
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_BASIC_ENABLED=${GF_AUTH_BASIC_ENABLED}
    entrypoint:
      - sh
      - -euc
      - |
        /run.sh
    healthcheck:
      test: ["CMD", "sh", "-c" ,"curl -s -f -o /dev/null http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - ${GRAFANA_PROVISIONING_PATH}:/etc/grafana/provisioning
