version: "3.8"
services:
  loki:
    image: grafana/loki:latest
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ${LOKI_CONFIG_PATH}:/etc/loki/config.yaml
    depends_on:
      - server
