# Prometheus main configuration file
#
# Global configuration:
#   - scrape_interval: How frequently to scrape targets (default: 1m)
#   - evaluation_interval: How frequently to evaluate rules (default: 1m)
global:
  # Scrape targets every 15 seconds
  scrape_interval: 15s
  # Evaluate rules every 10 seconds
  evaluation_interval: 10s

# Load alerting and recording rules from the specified file(s)
rule_files:
  - rules.yml # Alerting and recording rules

# Alertmanager configuration:
#   - List of Alertmanager instances to send alerts to
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093 # Alertmanager service

# Scrape configurations:
#   - Define monitoring jobs and their targets
scrape_configs:
  # Scrape Prometheus itself for metrics
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape node_exporter for host metrics
  - job_name: node_exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  # Scrape custom simple server
  - job_name: simple_server
    static_configs:
      - targets: ["server:8090"]
