route:
  # `group_wait` default is 30s, indicating the duration to hold off before sending an alert notification.
  group_wait: 5s
  receiver: webhook_receiver

receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: "http://grafana:3000/api/alerting/notifications/webhook"
        send_resolved: false
