apiVersion: 1

# This file provisions multiple datasources for Grafana
# - Loki: for log aggregation
# - OpenTelemetry (Tempo): for distributed tracing
# - Prometheus: for metrics

datasources:
  # Loki datasource for logs
  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
  # OpenTelemetry/Tempo datasource for traces
  - name: OpenTelemetry
    uid: OpenTelemetry
    type: tempo
    access: proxy
    url: http://otel-collector:4318
    isDefault: false
    editable: true
  # Prometheus datasource for metrics
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
