apiVersion: v1
kind: Service
metadata:
  name: portainer
spec:
  selector:
    app: portainer
  ports:
    - protocol: TCP
      port: {{ .Values.portainer.port }}
      targetPort: {{ .Values.portainer.port }}
